export const queryUsersByEmail = 'SELECT * FROM users where email = $1';
export const createUser = 'INSERT INTO users (email, password) values ($1, $2) returning *';
export const deleteUser = 'DELETE FROM users WHERE id = $1';
export const findUserById = 'SELECT * FROM users WHERE id = $1';
export const updateUserQuery = 'UPDATE users SET role=$1 WHERE id=$2 returning *';
export const queryProductTableByName = 'SELECT * FROM products WHERE productName =$1';
export const queryProductTableById = 'SELECT * FROM products WHERE id =$1';
export const insertProduct = 'INSERT INTO products (userId, productName, description, category, imageurl, quantity, unitPrice) values ($1, $2, $3, $4, $5, $6, $7) returning *';
export const queryAllProducts = 'SELECT * FROM products';
export const queryProductAdmin = 'SELECT * FROM products where id=$1 AND userId=$2';
export const updateProductQuery = 'UPDATE products SET description=$1, category=$2, imageurl=$3, quantity=$4, unitPrice=$5 WHERE id=$6 AND userId=$7 returning *';
export const deleteProductQuery = 'DELETE FROM products WHERE id=$1';
export const productQuantityAfterSale = 'UPDATE products SET quantity=$1 WHERE id=$2';
export const createSaleQuery = 'INSERT INTO sales (userId, saleItems, total) values ($1, $2, $3) returning *';
export const queryAllSales = 'SELECT * FROM sales';
export const queryOneSale = 'SELECT * FROM sales WHERE id =$1 AND userId=$2';
